WEB test/WEB test/Controllers/VartotojasController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OroUostoSistema.DatabaseOroUostas;
using OroUostoSistema.Helpers;
using OroUostoSistema.Models;

namespace OroUostoSistema.Controllers
{
    public class VartotojasController : Controller
    {
        private readonly DB _db = new DB();

        // GET: /Account/
        public ActionResult Index()
        {
            return View(_db.Users.ToList());
        }

        // GET: /Account/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uzsakovas uzsakovas = _db.Users.Find(id);
            if (uzsakovas == null)
            {
                return HttpNotFound();
            }
            return View(uzsakovas);
        }

        // GET: /Account/Create 
        // TODO example [Authorize(Roles="Administrators")]
        [AllowAnonymous]
        public ActionResult Registracija()
        {
            return View();
        }

        // POST: /Account/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Registracija([Bind(Include = "ID,Vardas,Pavarde,ElPastas,Numeris,Slaptazodis,ReSlaptazodis")] Uzsakovas uzsakovas)
        {
            if (!ModelState.IsValid) 
                return View(uzsakovas);
            uzsakovas.Registruoti(_db);
            return RedirectToAction("Index", "Klientas");
        }

        public ActionResult Prisijungimas()
        {

            return View(new UserModelView());
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Prisijungimas([Bind(Include = "Email,Password")] UserModelView prisijungimas)
        {
            var user = prisijungimas.Prisijungti(_db);
            if (user == null)
            {
                prisijungimas.Error = "Blogi prisijungimo duomenys";
                return View(prisijungimas);
            }

            PrisijungimoPagalba.Prisijungimas(Request.GetOwinContext(),user);
            Session["UserID"] = user.ID;
            return RedirectToAction("Index", "Klientas");
        }

        public ActionResult Atsijungti()
        {
            PrisijungimoPagalba.Atjungti(Request.GetOwinContext());
            return RedirectToAction("Index","Klientas");
        }

        // GET: /Account/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uzsakovas uzsakovas = _db.Users.Find(id);
            if (uzsakovas == null)
            {
                return HttpNotFound();
            }
            return View(uzsakovas);
        }

        // POST: /Account/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit([Bind(Include="ID,Vardas,Pavarde,ElPastas,Numeris,Slaptazodis")] Uzsakovas uzsakovas)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(uzsakovas).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(uzsakovas);
        }

        // GET: /Account/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uzsakovas uzsakovas = _db.Users.Find(id);
            if (uzsakovas == null)
            {
                return HttpNotFound();
            }
            return View(uzsakovas);
        }

        // POST: /Account/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Uzsakovas uzsakovas = _db.Users.Find(id);
            _db.Users.Remove(uzsakovas);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WEB test/WEB test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.20/angular.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/App")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>                
                @Html.ActionLink("Pagrindinis", "Index", "Klientas", null, new { @class = "navbar-brand" })
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Mano Profilis", "PasirinktiPrivilegija", "Klientas", null, new { @class = "navbar-brand" })
                    @Html.ActionLink("Mano bilietai", "GautiBilietus", "Klientas", new { id = Session["UserID"] }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Atsijungti", "Atsijungti", "Vartotojas", null, new {@class = "navbar-brand"})
                }
                else
                {
                    @Html.ActionLink("Registracija", "Registracija", "Vartotojas", null, new { @class = "navbar-brand" })
                    @Html.ActionLink("Prisijungimas", "Prisijungimas", "Vartotojas", null, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top:50px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

</body>
</html>